version: '3'

tasks:
  build:
    cmds:
      - task genpb-ts && npx tsc && cp *_pb.js dist/ && npx webpack
  genpb-cdts:
    cmds:
      - >
        protoc -I=../ echo.proto \
         --js_out=import_style=commonjs:. \
         --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:.
  genpb-ts:
    cmds:
      - >
        protoc -I=../ echo.proto \
         --js_out=import_style=commonjs:. \
         --grpc-web_out=import_style=typescript,mode=grpcwebtext:.